on: push
jobs:
    tox:
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}.x
          - run: pip install tox
          - run: tox -e py${{ matrix.python-version }}
        strategy:
            matrix:
                os:
                  - macOS-latest
                  - ubuntu-latest
                  - windows-latest
                python-version:
                  - 2
                  - 3
